(function () {
    const title = 'Aliens';

    const author = 'The story of Pine Bush, as told by Alex.';

    const body = `Pine Bush is a town not too far from nowhere and not too close to anywhere. More specifically, it’s a small, quiet town in an unimportant county of New York, far enough from the city to make it basically West Virginia.
    Pine Bush was founded in the early 1800’s as a settlement with not much more than a train station (much like where I grew up in Emerson, New Jersey but about a hundred years older). It’s got a mediocre school that looks like a McDonalds, and a population of less than two thousand. It’s got one supermarket and a surprising number of nearby vineyards. But all that aside, the people of Pine Bush are, for the most part, very standard Americans. That is except for one thing of course. They’ve regularly been seeing UFOs since the 60’s all over town.
    It’s important to note at this point that, while the literature created by the various Pine Bush extraterrestrial societies is seemingly limitless, my patience is… not. I could go into the current events and lectures I’ve found on the many… many sites related to UFOs and aliens and recount extensive research done into the way psychedelic experiences and alien encounters are related. I could try to debunk their beliefs and talk about murmurisms, cloud formations or the Air Force base nearby. I could even discuss the various players in the game, the absurd number of “researchers'' and “scholars” in the field, but the reality is I genuinely couldn't care less about these crackpots. They’re welcome to their opinion. I just want to know… why Pine Bush?
    Okay, so let’s start at what can easily be described as “the beginning”. In the Aug 25, 1984 edition of the New York Times, an article came out discussing the mass sighting from the night before. It quotes Mr. Peter Brandenberg, a middle-aged housing developer, saying “The UFO’s here! The UFO’s here.” He provided descriptions of a familiar phenomenon: the massive, house-sized “Westchester Boomerang”. Reports of the Boomerang were springing up a lot by this point. By the mid-80’s hundreds of reports of an unidentified flying object that seemed to blink in the night sky, stop mid-flight, and course-correct on a dime all while not making much more than a low humming sound. The reports were popping up all over the Hudson Valley, but especially in Pine Bush.
    The residents of Pine Bush began to join together. Reports were becoming standardized and local “UFOlogists” were gaining traction with hotlines that people could call to record their witness statements. Many of these witnesses were starting to gather at night on West Searsville Road, a small, nondescript residential street on the outskirts of town. Their goal was to experience the seemingly common occurrences of “bright lights like headlights in the sky” and “orbs in the sky”. The skywatchers continued well into the late 90’s until the police started cracking down on them over various property disputes (who could blame them, these folks were pretty much walking just anywhere, they were bound to end up somewhere they shouldn’t).
    The hiatus of the skywatchers was brief, however, and they came back into the full swing of things with the popularization of social media and the internet in general.
    As for the original question: “why Pine Bush?” I say, “why not?” Pine Bush is a fairly quaint, middle-class, semi-rural town. They get a lot of air traffic and they’ve got a natural suspicion of their neighboring Air Force base. They’ve got all the building blocks of a great place to see weird, blinky stuff in the sky at night. But, most importantly, the whole “UFO Capital of the Northeast” claim is great business and good, clean fun! The UFOlogy sites I looked at not only taught about the various conspiracy theories of extraterrestrial life, but they sold locally-sourced merchandise and taught a lot about various natural phenomena in the solar system from moon phases to some basic literature on how light physics works. They even have an annual fair (which is a fantastic place for an impromptu date on your first vacation with an incredible woman) that brings in tourists from multiple states away, and brings together the community as a whole to celebrate a quirky part of the Pine Bush experience with local faire and plenty of hometown pride.
    These extraterrestrial hunters may have strange and oftentimes ludacris interpretations of what they have seen over the years (look up the “Quantum Hologram Matrix”), but they put on a great show. It’s boring out in Nowhere’s-ville, New York, I totally get it.`;

    const id = 'aliens';

    const div = document.getElementById(id);
    div.innerHTML += `<h1>${title}</h1>`;
    div.innerHTML += `<p class='author'>${author}</p>`;
    div.innerHTML += body.split('\n').reduce(
        (acc, line) => `${acc}${line.trim() ? `<p class='story'>${line.trim()}</p>` : '<br>'}`,
        '',
    );
})();